### ISSUE TITLE
 Error: write after end

### ISSUE THREAD

**Issue by petermikitsh** [CollectionFS/Meteor-http-methods#39]
I am seeing this error thrown in development mode intermittently.

```
events.js:72
         throw er; // Unhandled 'error' event
               ^
 Error: write after end
     at writeAfterEnd (_stream_writable.js:132:12)
     at Gzip.Writable.write (_stream_writable.js:180:5)
     at ServerResponse.res.write (.../.meteor/packages/webapp/.1.1.5.p7wmz5++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:109:18)
     at ServerResponse.res.end (.../.meteor/packages/webapp/.1.1.5.p7wmz5++os+web.browser+web.cordova/npm/node_modules/connect/lib/middleware/compress.js:116:14)
     at sendResponseIfDone (packages/cfs:http-methods/http.methods.server.api.js:542:1)
     at IncomingMessage.<anonymous> (packages/cfs:http-methods/http.methods.server.api.js:567:1)
     at IncomingMessage.emit (events.js:92:17)
     at _stream_readable.js:943:16
     at process._tickCallback (node.js:419:13)
```

**Comment by petermikitsh** [comment]
I'm also working with SVG's. https://github.com/CollectionFS/Meteor-CollectionFS/issues/648

**Comment by hluz** [comment]
Getting this problem also with json and svg files at least. @oorabona mentions a fix: https://github.com/CollectionFS/Meteor-CollectionFS/issues/648#issuecomment-105909111

Would be great if this could be fixed and a new version published. Relying on this for a prod app...

**Comment by petermikitsh** [comment]
In the meantime, I am using transparent PNG's for prod apps. If and when I can find some time, I'd be happy to make a PR on this... but I don't think that'd be for awhile.

**Comment by hluz** [comment]
That workaround does not work for me... My files are not images but files of any type. :-(

**Comment by MichaelErmer** [comment]
Got the same error... most times the svg download works, but at randomly it just crashes the server.

meteor list
accounts-facebook         1.0.4  Login service for Facebook accounts
accounts-password         1.1.1  Password support for accounts
accounts-ui               1.1.5  Simple templates to add login widgets to an app
alanning:roles            1.2.13  Role-based authorization
aldeed:collection2        2.3.3  Automatic validation of insert and update operations on the client and server.
cfs:filesystem            0.1.2  Filesystem storage adapter for CollectionFS
cfs:graphicsmagick        0.0.18  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                0.0.33  GridFS storage adapter for CollectionFS
cfs:standard-packages     0.5.9  Filesystem for Meteor, collectionFS
dburles:spacebars-tohtml  1.0.0  Easily compile spacebars templates to html
email                     1.0.6  Send email messages
hitchcott:panzoom         1.0.1  A jQuery plugin for panning and zooming elements using CSS3
http                      1.1.0  Make HTTP calls to remote servers
iron:router               1.0.9  Routing specifically designed for Meteor
jparker:gravatar          0.3.1  Simple package to use gravatar images
launch-screen             1.0.2  Default and customizable launch screen on mobile.
meteor-platform           1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:aggregate     1.2.1  Proper MongoDB aggregations support for Meteor
momentjs:moment           2.10.3  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mrt:url                   0.0.3  url npm library wrapped in meteor
mrt:webshot               0.0.1  Webshot - NPM Screenshot Library using PhantomJS, repackaged For Meteor
nemo64:bootstrap          3.3.4_2  Highly configurable bootstrap integration.
pcel:messenger            1.4.2  HubSpot's Messenger packaged for Meteor
service-configuration     1.0.4  Manage the configuration for third-party services
spacebars-compiler        1.0.6  Compiler for Spacebars template language
stevezhu:lodash           3.9.3  A utility library delivering consistency, customization, performance, & extras.
tap:i18n                  1.5.0  A comprehensive internationalization solution for Meteor

**Comment by nikhildaga** [comment]
Same error
