### ISSUE TITLE
Problem with use `HTTP` in server?

### ISSUE THREAD

**Issue by thearabbit** [CollectionFS/Meteor-http-methods#44]
Problem with use `HTTP` in server?
```js
// Server
HTTP.methods({
    'list': function() {
        return '<b>Default content type is text/html</b>';
    }
});
```
get error
```js
W20151107-10:52:03.636(7)? (STDERR) C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20151107-10:52:03.637(7)? (STDERR)
        throw(ex);
W20151107-10:52:03.637(7)? (STDERR)
              ^
W20151107-10:52:03.638(7)? (STDERR) ReferenceError: HTTP is not defined W20151107-10:52:03.638(7)? (STDERR)     at cpanel/server/methods/http.js:10:1
W20151107-10:52:03.638(7)? (STDERR)     at D:\meteor-app\cpanel\.meteor\local\build\programs\server\app\cpanel\server\methods\http.js:25:4
W20151107-10:52:03.639(7)? (STDERR)     at D:\meteor-app\cpanel\.meteor\local\build\programs\server\boot.js:242:10
W20151107-10:52:03.640(7)? (STDERR)     at Array.forEach (native)
W20151107-10:52:03.640(7)? (STDERR)     at Function._.each._.forEach (C:\Users\Theara\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20151107-10:52:03.640(7)? (STDERR)     at D:\meteor-app\cpanel\.meteor\local\build\programs\server\boot.js:137:5
```
Please help me.

**Comment by DevinXian** [comment]
`meteor add cfs:http-methods`

**Comment by DevinXian** [comment]
Did you have `http` in your `.meteor/package`? if not, try `meteor add http`
